version: "3.3"
services:
  reverseproxy:
    build: ./proxy-config
    ports:
      - 80:80
  visapi:
    hostname: visapi
    depends_on:
      - reverseproxy
    build: ./api-server
    expose:
      - "3000"
    volumes:
      - ./api-server/config:/visulate-server/config
    environment:
      - GOOGLE_AI_KEY=${GOOGLE_AI_KEY}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}
  visui:
    hostname: visui
    depends_on:
      - reverseproxy
    build: ./ui
    expose:
      - "80"
  vissql:
    hostname: vissql
    depends_on:
      - reverseproxy
    build: ./query-engine
    expose:
      - "5000"
    volumes:
      - ./query-engine/sql2csv/config:/query-engine/sql2csv/config