# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{ .Release.Name }}-deployer-sa
# automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-tester"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  containers:
  - name: tester
    image: "{{ .Values.tester.image }}"
    imagePullPolicy: Always
    # volumeMounts:
    # - mountPath: /var/run/secrets/tokens
    #   name: vault-token
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: APP_INSTANCE_NAME
      value: {{ .Release.Name }}
  restartPolicy: Never
  serviceAccountName: {{ .Release.Name }}-deployer-sa
  # volumes:
  # - name: vault-token
  #   projected:
  #     sources:
  #     - serviceAccountToken:
  #         path: vault-token
  #         expirationSeconds: 3600
  #         audience: vault
