---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "visulate-llc-public", "product_id": "visulate-for-oracle", "partner_name": "Visulate"}'
spec:
  descriptor:
    type: Visulate for Oracle
    version: "{{ .Values.apiServer.image.tag }}"
    description: |-
      Visulate for Oracle is a Cloud-based application to browse and search Oracle databases.
      Users create connections from a central server to each database and then query them using REST APIs or a browser.

      ## Support

      Visulate offers email and github issue based support for Marketplace customers.
      Open a [GitHub issue](https://github.com/visulate/visulate-for-oracle/issues)
      or email [support@visulate.com](mailto:support@visulate.com) if you need help.

    maintainers:
    - name: Visulate
      url: https://github.com/visulate/visulate-for-oracle
    links:
    - description: 'Product documentation'
      url: https://docs.visulate.net
    notes: |-

      ### Quickstart

      Follow the steps in the Visulate for Oracle [quickstart guide](https://docs.visulate.net/pages/quickstart.html#kubernetes-deployment) to verify the application is working correctly.

      ### Database registration

      Identify the databases you want to document and follow the steps in the [database setup](https://docs.visulate.net/pages/database-setup.html)
      guide to create a Visulate account in each one. Create a database registration file and apply it to the cluster by following the instructions
      in the [database registration](https://docs.visulate.net/pages/database-registration.html) guide.

      **Tip:** the [troubleshooting](https://docs.visulate.net/pages/troubleshooting.html) guide includes instructions for how to diagnose and rectify failed connections.

      ### Configure the SQL Query Engine

      Follow the steps in the [Query Engine configuration](https://docs.visulate.net/pages/query-engine-config.html) guide.

  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
    - group: v1
      kind: ConfigMap
    - group: v1
      kind: Secret
    - group: v1
      kind: Service
    - group: apps/v1
      kind: Deployment
    - group: batch/v1
      kind: Job