---
x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  partnerId: visulate-llc-public
  solutionId: visulate-for-oracle

  publishedVersion: '$TAG'
  publishedVersionMetadata:
    releaseNote: >-
      v1.1 Adds SQL Query Engine
      v1.1.16 Fix issues identified during E-Business Suite testing
      v1.1.17 Display recent history on search screen
      v1.1.19 Bump highlight.js from 9.18.1 to 10.4.1 in /ui
      v1.1.20 Improve database connection performance and updates to support BMS migrations
      v1.1.21 Fix for orphaned BackendConfig bug
      v1.1.23 Support for handlebars template transformations
      v1.1.24 Security updates
      v1.1.25 Convert ingress spec to networking.k8s.io/v1
  images:
    '':
      properties:
        apiServer.image.repo:
          type: REPO_WITH_REGISTRY
        apiServer.image.tag:
          type: TAG
    ui:
      properties:
        ui.image.repo:
          type: REPO_WITH_REGISTRY
        ui.image.tag:
          type: TAG
    sql:
      properties:
        sql.image.repo:
          type: REPO_WITH_REGISTRY
        sql.image.tag:
          type: TAG
    util:
      properties:
        util.image:
          type: FULL
    ubbagent:
      properties:
        ubbagent.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  apiServer.replicas:
    type: integer
    default: 1
    description: Desired number of API server Pods
  apiServer.corsOriginWhitelist:
    type: string
    default: ""
    description: |
      Comma separated list of UI origin servers that are allowed to make API calls.
      Example:  https://mydomain.com, https://mydomain.net:445, http://35.45.9.55:8080
      Enter * to allow requests from any origin.  Most deployments can leave this blank
      to prevent cross origin requests.
  ui.replicas:
    type: integer
    default: 1
    description: Desired number of UI Pods
  sql.replicas:
    type: integer
    default: 1
    description: Desired number of Query Engine Pods
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - name
  - namespace
  - certificate
